apiVersion: apps/v1 
kind: Deployment
metadata:
  name: udr-deployment
spec:
  selector:
    matchLabels:
      app: free5gc-udr
  replicas: 1
  template:
    metadata:
      labels:
        app: free5gc-udr
    spec:
      containers:      
      - name: myapp-container
        image: andresache/udr
        ports:
        - containerPort: 29504
        imagePullPolicy: Always

---
kind: Service
apiVersion: v1
metadata:
  name: udr-service
  labels:
    app: free5gc-udr
spec:
  type: ClusterIP      
  selector:
    app: free5gc-udr
  ports:
  - protocol: TCP
    targetPort: 29504
    port: 29504
