apiVersion: apps/v1 
kind: Deployment
metadata:
  name: upf-deployment
spec:
  selector:
    matchLabels:
      app: free5gc-upf
  replicas: 1
  template:
    metadata:
      labels:
        app: free5gc-upf
    spec:
      containers:      
      - name: myapp-container
        image: andresache/upf
        ports:
        - containerPort: 29517
          name: upf-sbi
          protocol: TCP        
        - containerPort: 2152
          name: upf-n3
          protocol: UDP
        - containerPort: 8805  
          name: upf-n4
          protocol: UDP
        imagePullPolicy: Always
        securityContext:
          privileged: true
          capabilities:
            add: ["NET_ADMIN", "NET_RAW", "NET_BIND_SERVICE", "SYS_TIME"]
            # lifecycle:
            #postStart:
            #exec:
            # command: ["/bin/sh", "-c", "sleep 5; ./free5gc-upfd -c upfcfg.yaml"]
      dnsPolicy: ClusterFirst

