apiVersion: v1
kind: Service
metadata:
  name: upf-service
  labels:
    app: free5gc-upf
spec:
  type: ClusterIP
  selector:
    app: free5gc-upf
  clusterIP: None
  ports:
  - name: sbi
    targetPort: 29517
    port: 29517
    protocol: TCP
  - name: upf-n3
    protocol: UDP
    targetPort: 2152
    port: 2152
  - name: upf-n4
    targetPort: 8805
    port: 8805
    protocol: UDP

