apiVersion: apps/v1 
kind: Deployment
metadata:
  name: ausf-deployment
spec:
  selector:
    matchLabels:
      app: free5gc-ausf
  replicas: 1
  template:
    metadata:
      labels:
        app: free5gc-ausf
    spec:
      containers:      
      - name: myapp-container
        image: andresache/ausf
        ports:
        - containerPort: 29509
        imagePullPolicy: Always

---
kind: Service
apiVersion: v1
metadata:
  name: ausf-service
  labels:
    app: free5gc-ausf
spec:
  type: ClusterIP      
  selector:
    app: free5gc-ausf
  ports:
  - protocol: TCP
    targetPort: 29509
    port: 29509      

