apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nrf-deployment
spec:
  selector:
    matchLabels:
      app: free5gc-nrf
  replicas: 1
  template:
    metadata:
      labels:
        app: free5gc-nrf
    spec:
      containers:      
      - name: myapp-container
        image: andresache/nrf
        ports:
        - containerPort: 29510
        imagePullPolicy: Always

---
kind: Service
apiVersion: v1
metadata:
  name: nrf-service
  labels:
    app: free5gc-nrf
spec:
  type: ClusterIP      
  selector:
    app: free5gc-nrf
  ports:
  - protocol: TCP
    targetPort: 29510
    port: 29510      
  
