apiVersion: apps/v1 
kind: Deployment
metadata:
  name: pcf-deployment
spec:
  selector:
    matchLabels:
      app: free5gc-pcf
  replicas: 1
  template:
    metadata:
      labels:
        app: free5gc-pcf
    spec:
      containers:      
      - name: myapp-container
        image: andresache/pcf
        ports:
        - containerPort: 29507
        imagePullPolicy: Always

---
kind: Service
apiVersion: v1
metadata:
  name: pcf-service
  labels:
    app: free5gc-pcf
spec:
  type: ClusterIP      
  selector:
    app: free5gc-pcf
  ports:
  - protocol: TCP
    targetPort: 29507
    port: 29507      

