apiVersion: apps/v1 
kind: Deployment
metadata:
  name: smf-deployment
spec:
  selector:
    matchLabels:
      app: free5gc-smf
  replicas: 1
  template:
    metadata:
      labels:
        app: free5gc-smf
    spec:
      containers:      
      - name: myapp-container
        image: andresache/smf
        ports:
        - containerPort: 29502
        - containerPort: 8805  
        imagePullPolicy: Always

---
kind: Service
apiVersion: v1
metadata:
  name: smf-service
  labels:
    app: free5gc-smf
spec:
  type: ClusterIP      
  selector:
    app: free5gc-smf
  ports:
  - protocol: TCP
    name: smf-sbi
    targetPort: 29502
    port: 29502
  - protocol: UDP
    name: smf-n4
    targetPort: 8805
    port: 8805  
