apiVersion: apps/v1 
kind: Deployment
metadata:
  name: webui-deployment
spec:
  selector:
    matchLabels:
      app: free5gc-webui
  replicas: 1
  template:
    metadata:
      labels:
        app: free5gc-webui
    spec:
      containers:      
      - name: myapp-container
        image: andresache/webui
        ports:
        - containerPort: 5000
        imagePullPolicy: Always

---
kind: Service
apiVersion: v1
metadata:
  name: webui-service
  labels:
    app: free5gc-webui
spec:
  type: NodePort      
  selector:
    app: free5gc-webui
  ports:
  - protocol: TCP
    targetPort: 5000
    port: 5000
